### ISSUE TITLE
Unable to update dataset with new DOI information

### ISSUE THREAD

**Issue by AYSung** [VariantEffect/mavedb-api#193]
I published a score set as requested by a reviewer but the DOI linking was not working at the time. The publisher has asked that the dataset be linked to the DOI when it is published, but when I access the score set there is no way to edit the external DOI and raw read links.

**Comment by afrubin** [comment]
@AYSung Thanks for your report. Can you put the URN of the dataset you're having trouble with here?

If I understand correctly, you have an existing score set and want to edit the metadata so that it correctly links to to the raw reads. Is that right?

MaveDB is not able to mint DOIs, but the urn accession number given when the dataset is published will be stable and can be put in your publication.

**Comment by AYSung** [comment]
Hi Alan,

The URN is mavedb:00000663-a. I would like to edit the metadata to include
the doi: 10.1038/s42255-024-01042-7 and a link to the raw reads at
https://www.ncbi.nlm.nih.gov/bioproject/PRJNA1007392. Appreciate your help!

Best,
Andrew

**Comment by afrubin** [comment]
@AYSung Thanks, we'll look into this and see if there's a bug stopping you from editing the metadata yourself.

I see that the DOI is to a paper. We'd rather wait until the paper has been indexed in PubMed and link it to the record that way, since that will enable searching by author and other publication attributes, as well as letting us format the reference properly on the MaveDB website. I hope that will satisfy the journal!

**Comment by AYSung** [comment]
Thanks, that makes sense! Should I ping you again when the paper is indexed
on PubMed?

Best,
Andrew

**Comment by afrubin** [comment]
Yes, please do!

**Comment by AYSung** [comment]
Hi Alan,

The paper has been indexed on Pubmed
https://pubmed.ncbi.nlm.nih.gov/38720117/ - Let me know if you need any
more information and thanks again for the help!

Best,
Andrew

**Comment by jstone-uw** [comment]
Hi Andrew, we wanted to let you know that the Pubmed link, DOI, and raw reads link have been added to the experiment and score set. Thanks for letting us know about this! We'll address the underlying issue that prevented you from attaching these.

Best,
Jeremy

**Comment by AYSung** [comment]
Awesome, thank you so much!

Best,
Andrew

**Comment by bencap** [comment]
Closing as completed based on the above discussion.
