### ISSUE TITLE
Editing a score set causes loss of scores.

### ISSUE THREAD

**Issue by jstone-dev** [VariantEffect/mavedb-api#245]
It was reported that when a published score set's metadata (text fields, etc.) are updated, the variants and scores are deleted.

The intended behavior is that the variant validation process is re-run, and variants are re-created. It seems possible that this bug report actually relates to the period between updating the score set and having the variants re-validated. If so, we may just need to make the validation status clearer so that after clicking update, it doesn't appear to the user as if the scores have been lost.

**Comment by bencap** [comment]
@afrubin Was it possible that when you observed this it was because the worker was still processing the updated variants? I wasn't able to reproduce.

There is a period of time between clicking update and when the worker is not done where no variants will be shown.
![Image](https://github.com/user-attachments/assets/d03c2639-51fc-4466-bc00-bed820baaca9)

**Comment by bencap** [comment]
Believed to be addressed via #260.
