### ISSUE TITLE
Experiments should return their score set URNs

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/mavedb-api#47]
Right now requesting an experiment only returns the number of score sets but not their URNs or contents. Instead, the score set includes the full experiment object for its parent.

By contrast, experiment sets include the full experiment record for each of their child experiments.

The behavior of both of these should be harmonized in some way.

One option is to include all child records as part of the parent, which could make some experiment sets rather large (since they would also include all the score sets associated with the experiments).

Another option is to just include URNs for the parent and child records in each experiment set, experiment, and score set. This would allow API users to easily traverse the dataset without making each individual response too big.

@jstone-uw @EstelleDa would changing this have major implications for how https://github.com/VariantEffect/mavedb-ui functions?

**Comment by jstone-uw** [comment]
We can adapt the UI to whatever we decide is best for the API.

Currently, the experiment endpoint just returns the number of score sets, and you can make a second call to /experiment/{id}/scoresets to fetch these. The motivation is that if you request one score set, it's likely that you want to know what experiment (and experiment set) it belongs to, and this doesn't increase the response size too much; whereas if you request an experiment, you may or may not need to know all the details of its score sets, and there could be many of them, so the response size might be multiplied significantly. (Score sets are also larger than experiments.)

Or, in general: Our document structure for experimental results is hierarchical with a well-defined first ancestor (the experiment set). It doesn't introduce much overhead to provide parent details, but I'd prefer to leave downward traversal to the client's discretion.

What I definitely want to avoid is expanding the tree in both directions, since this leads to circularity in API responses. There are ways to deal with this, like JSOG, but they require some logic on the client side to reconstruct the references, and we want this API to be consumable easily by others.

But if some use case would benefit from having a list of score sets URNs in the experiment response, we could add a `scoresetUrns` property to the experiment view model and run a query to populate it, as in your last suggestion. What do you think?

We could also replace `experiment` with `experimentUrn` in the score set details, and some clients would have to make a second request if they wanted the parent (and another one if they wanted the experiment set too). I don't really think it's inconsistent to include ancestors but not descendants in API responses, but it wouldn't be a big change if others prefer this.

**Comment by afrubin** [comment]
> Currently, the experiment endpoint just returns the number of score sets, and you can make a second call to /experiment/{id}/scoresets to fetch these.

Great, I wasn't aware that this was the case when I opened this issue! This is a very reasonable implementation and I'm fine with leaving things like this. Sounds like this is a fix through documentation rather than something new that needs to get implemented.

> What I definitely want to avoid is expanding the tree in both directions, since this leads to circularity in API responses. 

I completely agree with this.

> But if some use case would benefit from having a list of score sets URNs in the experiment response, we could add a scoresetUrns property to the experiment view model and run a query to populate it, as in your last suggestion. What do you think?

As I inadvertently demonstrated, this would be more intuitive for people who are just poking around in the API, but it will result in people writing for loops to retrieve each scoreset individually by URN rather than using /experiment/{id}/scoresets. So maybe this is not worth adding?

> We could also replace experiment with experimentUrn in the score set details, and some clients would have to make a second request if they wanted the parent (and another one if they wanted the experiment set too). I don't really think it's inconsistent to include ancestors but not descendants in API responses, but it wouldn't be a big change if others prefer this.

The benefit to having the experiment included in the scoreset is that then users get a complete record describing the data. I think that having experimentsets give the full experiment (descendants) and scoresets give the full experiment (ancestors) is inconsistent but very functional in terms of how we expect people to use the service.

There's a bit of duplicated data when requesting /experiment/{id}/scoresets since every scoreset gets its own copy of the experiment, but I don't anticipate that will blow out the size of the responses.

It makes sense to me that we should leave this as it is and wait until we see how people are actually using the API before we try to solve problems that may not exist. I'll close this for now but we can always come back to it.

**Comment by EstelleDa** [comment]
Mavedb-ui currently calls /experiment/{id}/scoresets to get associated scoresets in Experiment page. Then target genes data are extracted from these scoresets.
