### ISSUE TITLE
Validator raises error but score set is still saved in database

### ISSUE THREAD

**Issue by EstelleDa** [VariantEffect/mavedb-api#72]
If sequence and sequence type don't match, `validate_and_standardize_dataframe_pair` in `upload_score_set_variant_data` function will raise an importing scores and counts error that leads score and count files can't be saved in database and website stays in creating new score set page. However, a score set without score_columns and count_columns is saved in database and it appears in user's Dashboard unpublished score set list.

**Comment by afrubin** [comment]
Since adding a new score set is a two-step process with respect to the API, this seems like expected behavior. First the user submits all the metadata with a POST request to `"/score-sets/"`. If that is successful, then can they add the files as a second POST to `"/score-sets/{urn}/variants/data"` using the temporary URN.

As of https://github.com/VariantEffect/mavedb-api/commit/6e3da059021faf0311ef6faead46d5b27891d8b0, which is now running in production, users cannot publish one of these score sets that doesn't have variants, so having these score sets without variants around is not a problem.

It does sound like this is something that we could handle better on the UI side, by updating the dashboard to somehow highlight temporary score sets. We should also make sure that the process for a website user who wants to only upload scores and not change other metadata is findable and easy to follow.
