### ISSUE TITLE
Improving usage statistics

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/mavedb-api#80]
To demonstrate the impact of MaveDB, we are often called upon to provide detailed usage statistics. However, our current ability to collect this important information is limited.

We don't want to track individual users, but we should be collecting the following aggregated information:
* Number of page views
* Number of unique users
* Number of downloads for each dataset
* Number of external API requests
* Other things?

We'll want to collect these statistics by date and by country so that we can show that we have an international user base and also produce breakdowns over various time periods.

**Comment by jstone-uw** [comment]
We discussed using Google Analytics for much of this, because with little effort it will provide deeper information than we're likely to want to collect ourselves.

In conjunction with this, I'll add basic logging of API requests, which in particular will allow us to track dataset downloads that Google Analytics will miss. For each API request, we can log the authentication method; all software clients should be using access keys rather than ORCID.
